; Local development PJSIP configuration.

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
local_net=172.21.0.0/16
external_media_address=192.168.100.155

[1000]
type=endpoint
context=univoice-incoming
disallow=all
allow=ulaw
auth=1000-auth
aors=1000
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

[1000-auth]
type=auth
auth_type=userpass
username=1000
password=change-me

[1000]
type=aor
max_contacts=1