; Local development PJSIP configuration.

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[1000]
type=endpoint
context=univoice-incoming
disallow=all
allow=ulaw
auth=1000-auth
aors=1000

[1000-auth]
type=auth
auth_type=userpass
username=1000
password=change-me

[1000]
type=aor
max_contacts=1
